---
title: "Likert"
output: html_document
date: "2024-09-10"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r import data}
#Data for first set of questions

first_questions_data <- structure(list(Item = c("I spend more time educating myself on abortion legislation.", 
"I spend more time educating myself on abortion legislation.", 
"I spend more time educating other providers on abortion legislation.", 
"I spend more time educating other providers on abortion legislation.", 
"I spend more time discussing abortion legislation with my patients.", 
"I spend more time discussing abortion legislation with my patients.", 
"I spend more time worrying about my patients.", "I spend more time worrying about my patients.", 
"I spend more time coordinating abortion care for my patients.", 
"I spend more time coordinating abortion care for my patients.", 
"I have felt torn between providing information about abortion and complying with legislation.", 
"I have felt torn between providing information about abortion and complying with legislation.", 
"I have felt an increase in time pressure due to gestational age limitations.", 
"I have felt an increase in time pressure due to gestational age limitations.", 
"My patients have been negatively impacted.", "My patients have been negatively impacted.", 
"My job-related stress has increased.", "My job-related stress has increased.", 
"My job satisfaction has decreased.", "My job satisfaction has decreased."
), type = structure(c(1L, 2L, 1L, 2L, 1L, 2L, 1L, 2L, 1L, 2L, 
1L, 2L, 1L, 2L, 1L, 2L, 1L, 2L, 1L, 2L), levels = c("GCs in protective states", 
"GCs in restrictive states"), class = "factor"), `Strongly Disagree` = c(0, 
0, 0, 1.9, 7.1, 1.9, 35.7, 1.9, 71.4, 17.3, 71.4, 44.2, 42.9, 
9.6, 35.7, 1.9, 35.7, 9.6, 35.7, 17.3), `Somewhat Disagree` = c(28.6, 
1.9, 42.9, 15.4, 28.6, 1.9, 7.1, 7.7, 21.4, 13.5, 14.3, 15.4, 
14.3, 19.2, 7.1, 5.8, 28.6, 3.8, 28.6, 9.6), `Neither Agree nor Disagree` = c(0, 
15.4, 21.4, 11.5, 14.3, 9.6, 28.6, 3.8, 7.1, 19.2, 14.3, 17.3, 
14.3, 13.5, 21.4, 3.8, 21.4, 19.2, 28.6, 32.7), `Somewhat Agree` = c(57.1, 
25, 35.7, 30.8, 42.9, 28.8, 28.6, 26.9, 0, 9.6, 0, 9.6, 28.6, 
23.1, 21.4, 13.5, 14.3, 38.5, 7.1, 36.5), `Strongly Agree` = c(14.3, 
57.7, 0, 40.4, 7.1, 57.7, 0, 59.6, 0, 40.4, 0, 13.5, 0, 34.6, 
14.3, 75, 0, 28.8, 0, 3.8)), row.names = c(NA, -20L), class = c("tbl_df", 
"tbl", "data.frame"))
```

```{r}
# Display the first few rows of the data
head(first_questions_data)
```

```{r}
second_questions_data <- structure(list(Item = c("a ban on emergency contraception.", 
"a ban on emergency contraception.", "a complete ban on abortion.", 
"a complete ban on abortion.", "an early gestational age ban at 6-weeks' gestation.", 
"an early gestational age ban at 6-weeks' gestation.", "an early gestational age ban between 8- and 10-weeks' gestation.", 
"an early gestational age ban between 8- and 10-weeks' gestation.", 
"an early gestational age ban between 10- and 18-weeks' gestation.", 
"an early gestational age ban between 10- and 18-weeks' gestation.", 
"a reason-based abortion ban.", "a reason-based abortion ban."
), type = c("GC students", "prenatal GCs", "GC students", "prenatal GCs", 
"GC students", "prenatal GCs", "GC students", "prenatal GCs", 
"GC students", "prenatal GCs", "GC students", "prenatal GCs"), 
    `Strongly Disagree` = c(45.9, 20.9, 32.4, 26.4, 27, 24.2, 
    24.3, 18.7, 8.1, 8.8, 13.5, 20.9), `Somewhat Disagree` = c(24.3, 
    23.1, 37.8, 20.9, 40.5, 23.1, 40.5, 27.5, 43.2, 22, 27, 15.4
    ), `Neither Agree or Disagree` = c(5.4, 12.1, 0, 6.6, 2.7, 
    6.6, 0, 6.6, 2.7, 12.1, 13.5, 9.9), `Somewhat Agree` = c(10.8, 
    20.9, 13.5, 24.2, 13.5, 25.3, 16.2, 26.4, 21.6, 30.8, 27, 
    31.9), `Strongly Agree` = c(13.5, 22, 16.2, 20.9, 16.2, 19.8, 
    16.2, 19.8, 24.3, 25.3, 18.9, 20.9)), row.names = c(NA, -12L
), class = c("tbl_df", "tbl", "data.frame"))
```

```{r}
# Display the first few rows of the data
head(second_questions_data)
```


```{r}
third_questions_data <- structure(list(Item = c("I would preferentially apply to jobs in states that protect abortion access.", 
"I would preferentially apply to jobs in states that protect abortion access."
), type = c("GC students", "prenatal GCs"), `Strongly Disagree` = c(2.7, 
3.3), `Somewhat Disagree` = c(2.7, 9.9), `Neither Agree or Disagree` = c(8.1, 
8.8), `Somewhat Agree` = c(21.6, 35.2), `Strongly Agree` = c(64.9, 
41.8)), class = c("tbl_df", "tbl", "data.frame"), row.names = c(NA, 
-2L))
```

```{r}
# Display the first few rows of the data
head(third_questions_data)
```

```{r}
library(likert) 
library(ggplot2)
library(ggtext)
```

```{r}
# get data ready
first_plot = likert::likert(summary = first_questions_data[, c(1, 3:7)], 
                        grouping = first_questions_data$type)
second_plot = likert::likert(summary = second_questions_data[, c(1, 3:7)], 
                        grouping = second_questions_data$type)
third_plot = likert::likert(summary = third_questions_data[, c(1, 3:7)], 
                        grouping = third_questions_data$type)
```

```{r}
# Check if summary data is ready with percentages because this function works
summary(first_plot)
```

```{r}
# Check if summary data is ready with percentages because this function works
summary(second_plot)
```

```{r}
# Check if summary data is ready with percentages because this function works
summary(third_plot)
```

```{r}
#Plot with custom titles
plot(first_plot) + ggtitle("As a result of the *Dobbs* decision...") + theme(title = ggtext::element_markdown())
```

```{r}
#Plot with custom titles
plot(second_plot) + ggtitle("I would be willing to work as a prenatal GC in a state with...")
```

```{r}
plot(third_plot)
```

